import type { Metadata } from "next";

import "./globals.css";
import { StoreProvider } from "@/lib/StoreProvider";

import { ProvidersSession } from "@/lib/SessionProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <StoreProvider>
          <ProvidersSession>
            {children}
          </ProvidersSession>
        </StoreProvider>
      </body>
    </html>
  );
}
